/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Emp_profile;
import model.HR_product;

/**
 *
 * @author Hitesh
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Emp_profile emp_info;
    String filename;
    
    public CreateJPanel(Emp_profile emp_info) {
        initComponents();
        this.emp_info = emp_info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtEmpid = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        txtGen = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtLevel = new javax.swing.JLabel();
        txtInfo = new javax.swing.JLabel();
        txtPos = new javax.swing.JLabel();
        txtCell = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtEmpId = new javax.swing.JTextField();
        jtxtAge = new javax.swing.JTextField();
        jtxtGen = new javax.swing.JTextField();
        jtxtSt_date = new javax.swing.JTextField();
        jtxtLevel = new javax.swing.JTextField();
        jtxtTinfo = new javax.swing.JTextField();
        jtxtPos = new javax.swing.JTextField();
        jCellp = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jImgAtt = new javax.swing.JLabel();
        jUpImg = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Employee Profile");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtName.setText("Name");

        txtEmpid.setText("Employee ID");

        txtAge.setText("Age");

        txtGen.setText("Gender");

        txtDate.setText("Start date");

        txtLevel.setText("Level");

        txtInfo.setText("Team Info");

        txtPos.setText("Position title");

        txtCell.setText("Cell phone number");

        txtEmail.setText("Email");

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jtxtPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPosActionPerformed(evt);
            }
        });

        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jImgAtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jImgAtt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImgAtt.setText("Preview");
        jImgAtt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jImgAtt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jUpImg.setBackground(new java.awt.Color(255, 255, 153));
        jUpImg.setText("Upload");
        jUpImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtEmpid)
                            .addComponent(txtAge)
                            .addComponent(txtGen)
                            .addComponent(txtDate)
                            .addComponent(txtLevel)
                            .addComponent(txtInfo)
                            .addComponent(txtPos)
                            .addComponent(txtCell)
                            .addComponent(txtEmail))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtName)
                            .addComponent(jtxtEmpId)
                            .addComponent(jtxtAge)
                            .addComponent(jtxtGen)
                            .addComponent(jtxtSt_date)
                            .addComponent(jtxtLevel)
                            .addComponent(jtxtTinfo)
                            .addComponent(jtxtPos)
                            .addComponent(jCellp)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jImgAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jUpImg)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtCell, txtDate, txtEmail, txtEmpid, txtGen, txtInfo, txtLevel, txtName, txtPos});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmpid)
                            .addComponent(jtxtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge)
                            .addComponent(jtxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGen)
                            .addComponent(jtxtGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate)
                            .addComponent(jtxtSt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLevel)
                            .addComponent(jtxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInfo)
                            .addComponent(jtxtTinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos)
                            .addComponent(jtxtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCell)
                            .addComponent(jCellp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail)))
                    .addComponent(jImgAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jUpImg))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jtxtName.getText();
        int employeeId = Integer.parseInt(jtxtEmpId.getText());
        int age = Integer.parseInt(jtxtAge.getText());
        String gender = jtxtGen.getText();
        String start_date = jtxtSt_date.getText();
        int level = Integer.parseInt(jtxtLevel.getText());
        String team_info = jtxtTinfo.getText();
        String position_title = jtxtPos.getText();
        long phone_no = Long.parseLong(jCellp.getText());
        String email = jtxtEmail.getText();
//        String photo = jUpImg.getText();
        
        HR_product emData = emp_info.addData();
        
        emData.setName(name);
        emData.setEmployeeId(employeeId);
        emData.setAge(age);
        emData.setGender(gender);
        emData.setStart_date(start_date);
        emData.setLevel(level);
        emData.setTeam_info(team_info);
        emData.setPosition_title(position_title);
        emData.setPhone_no(phone_no);
        emData.setEmail(email);
        emData.setPhoto(filename);
        

        JOptionPane.showMessageDialog(this, "New Employee Data Added.");
        jImgAtt.setIcon(null);

        jtxtName.setText("");
        jtxtEmpId.setText("");
        jtxtAge.setText("");
        jtxtGen.setText("");
        jtxtSt_date.setText("");
        jtxtLevel.setText("");
        jtxtTinfo.setText("");
        jtxtPos.setText("");
        jCellp.setText("");
        jtxtEmail.setText("");
        
        
    
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPosActionPerformed

    private void jUpImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpImgActionPerformed
        // TODO add your handling code here:
        JFileChooser attImg = new JFileChooser();
        int showimg = attImg.showOpenDialog(null);
        
//        if(showimg == JFileChooser.APPROVE_OPTION)
        File fil = attImg.getSelectedFile();
        filename = fil.getAbsolutePath();
        Image getAbsolutePath = null;
        ImageIcon pre = new ImageIcon(filename);
        Image image = pre.getImage().getScaledInstance(155,155,Image.SCALE_SMOOTH);
        pre = new ImageIcon(image);
        jImgAtt.setIcon(pre);
        
        
    }//GEN-LAST:event_jUpImgActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCellp;
    private javax.swing.JLabel jImgAtt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jUpImg;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtEmpId;
    private javax.swing.JTextField jtxtGen;
    private javax.swing.JTextField jtxtLevel;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPos;
    private javax.swing.JTextField jtxtSt_date;
    private javax.swing.JTextField jtxtTinfo;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtCell;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtEmpid;
    private javax.swing.JLabel txtGen;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtLevel;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPos;
    // End of variables declaration//GEN-END:variables
}
